### ISSUE TITLE
404 in Google Drive link

### ISSUE THREAD

**Issue by chensiweiTHU** [LarryDong/Event_HDR_Dataset#1]
Hello,
I am interested in your dataset, but I found 404 in your link. Will you publish a newer link in the future? thx.

**Comment by LarryDong** [comment]
通过网盘分享的文件：event-hdr-dataset
链接: https://pan.baidu.com/s/1764vCwayRWNMfnrrHeHK4w 提取码: xawy 

论文已经改不出来了，后面就把数据集删了。7天有效，请不要扩散使用。谢谢

**Comment by Mortal825** [comment]
Hello,
I am very interested in your dataset, but the download link seems to be unavailable (404). Could you please let me know if there will be an updated link released in the future?
